apiVersion: v1
kind: Secret
metadata:
  name: mentor-secret
data:
  DB_HOST: "{{ db_host | b64encode }}"
  DB_PORT: "{{ db_port | b64encode }}"
  DB_NAME: "{{ db_name | b64encode }}"
  DB_USER: "{{ db_user | b64encode }}"
  DB_PASSWORD: "{{ db_password | b64encode }}"
  SECRET_KEY: "{{ django_secret_key | b64encode }}"
  ACME_EMAIL: "{{ acme_email | b64encode }}"