# pull repo into seperate directory to allow branches other than k3s
- name: Clone / pull git repo
  ansible.builtin.git:
    repo: 'https://github.com/adamuremek/mentorship_program.git'
    dest: "{{ absolute_project_path }}/repo"
    update: yes
    version: SAML-Auth

- name: Build Django Docker image
  community.docker.docker_image_build:
    name: "localhost:5000/project-kubernetes"
    path: "{{ absolute_project_path }}/repo"
    dockerfile: ./Dockerfile
    rebuild: always

- name: Push Django image to local repository
  community.docker.docker_image_push:
    name: "localhost:5000/project-kubernetes"

- name: Build Nginx Docker image
  community.docker.docker_image_build:
    name: "localhost:5000/nginx-kubernetes"
    path: "{{ absolute_project_path }}/repo/nginx"
    dockerfile: ./Dockerfile
    rebuild: always

- name: Push Nginx image to local repository
  community.docker.docker_image_push:
    name: "localhost:5000/nginx-kubernetes"