version: '3.8'

volumes:
  # Create a volume for postgres to persist data
  postgres_data:
  # Create a volume for static files
  static_volume:
  
services:
  # Container for the database
  db:
    image: postgres:16
    # Set environment variables for the database
    environment:
      - POSTGRES_DB=development
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    # Mount the postgres data volume
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # Map postgres port inside the container to the external port
    #  to allow db connections outside of the container
    ports:
        # External_port:internal_port
      - 7654:5432
  # Container for the django project
  web:
    build: 
      context: .
      dockerfile: ./docker/Dockerfile
    # Run the django server when contriner starts
    command: gunicorn -w 4 mentorship_program_project.wsgi:application --bind 0.0.0.0:8000
    # Mount the local project directory to the container
    volumes:
      - ./mentorship_program_project:/mentorship_program_project
      - static_volume:/static
    expose:
      - 8000
    # Set environment variables inside the container from .env file
    env_file:
      - ./docker/.env
    # Make sure db container is running before starting this one
    depends_on:
      - db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/static
    ports:
      - 1337:80
    depends_on:
      - web
  
