# Generated by Django 5.0.1 on 2024-03-11 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship_program_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='str_experience',
            field=models.CharField(default='', max_length=50),
        ),
    ]
