# Generated by Django 5.0.1 on 2024-02-09 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship_program_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='strInterest',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
