# Generated by Django 5.0.1 on 2024-02-14 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship_program_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='imgUserProfile',
            field=models.ImageField(default='images/default_profile_picture.png', upload_to='images/'),
        ),
    ]
