# Generated by Django 5.0.1 on 2024-02-08 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship_program_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_interests',
            name='intInterestID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentorship_program_app.interests'),
        ),
        migrations.AlterField(
            model_name='user_interests',
            name='intUserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentorship_program_app.users'),
        ),
    ]
