# Generated by Django 5.0.1 on 2024-02-08 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship_program_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='strPasswordSalt',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='clsEmailAddress',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
