# Generated by Django 5.0.1 on 2024-02-24 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship_program_app', '0002_alter_user_imguserprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='orginization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mentorship_program_app.organization'),
        ),
        migrations.AlterField(
            model_name='user',
            name='strPasswordHash',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='strPasswordSalt',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
