# Generated by Django 5.0.1 on 2024-02-09 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship_program_app', '0002_alter_interest_strinterest'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='isDefaultInterest',
            field=models.BooleanField(default=False),
        ),
    ]
