# Generated by Django 5.0.1 on 2024-03-11 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship_program_app', '0002_mentor_str_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='int_recommendations',
        ),
        migrations.AddField(
            model_name='mentor',
            name='organization',
            field=models.ManyToManyField(to='mentorship_program_app.organization'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='admins',
            field=models.ManyToManyField(related_name='administered_organizations', to='mentorship_program_app.mentor'),
        ),
    ]
