# Generated by Django 5.0.1 on 2024-02-20 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship_program_app', '0003_alter_user_strpasswordhash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='str_role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Mentor', 'Mentor'), ('Mentee', 'Mentee'), ('MentorPending', 'Mentor Pending'), ('Banned', 'Banned'), ('Graduated', 'Graduated'), ('Declined', 'Declined')], default='', max_length=15),
        ),
    ]
