# Generated by Django 5.0.1 on 2024-03-12 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship_program_app', '0003_remove_mentor_int_recommendations_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='cls_date_of_birth',
            new_name='str_last_login_date',
        ),
    ]
