# Generated by Django 5.0.1 on 2024-03-12 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship_program_app', '0004_rename_cls_date_of_birth_user_str_last_login_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='str_bio',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.DeleteModel(
            name='Biographies',
        ),
    ]
