# Generated by Django 5.0.1 on 2024-02-20 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship_program_app', '0004_alter_user_strrole'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bln_account_disabled',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bln_active',
        ),
    ]
