# Generated by Django 5.0.1 on 2024-03-12 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship_program_app', '0005_user_str_bio_delete_biographies'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentee',
            name='mentor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mentorship_program_app.mentor'),
        ),
    ]
