# Generated by Django 5.0.1 on 2024-02-22 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship_program_app', '0006_user_blnaccountdisabled_user_blnactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='strRole',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Mentor', 'Mentor'), ('Mentee', 'Mentee'), ('MentorPending', 'Mentor Pending'), ('Graduated', 'Graduated'), ('Declined', 'Declined')], default='', max_length=15),
        ),
    ]
