# Generated by Django 5.0.1 on 2024-03-12 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship_program_app', '0006_mentee_mentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemlogs',
            name='specified_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mentorship_program_app.user'),
        ),
    ]
