# Generated by Django 5.0.1 on 2024-03-13 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship_program_app', '0007_systemlogs_specified_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemlogs',
            name='str_event',
            field=models.CharField(choices=[('Logon', 'Logon Event'), ('Create Mentorship', 'Create Mentorship Event')], default='', max_length=500),
        ),
    ]
