# Generated by Django 5.0.1 on 2024-02-22 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship_program_app', '0007_alter_user_strrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorshiprequest',
            name='mentee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentee_to_mentor', to='mentorship_program_app.user'),
        ),
        migrations.AlterField(
            model_name='mentorshiprequest',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_to_mentee', to='mentorship_program_app.user'),
        ),
    ]
