# Generated by Django 5.0.1 on 2024-02-23 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship_program_app', '0011_alter_mentorshiprequest_mentor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorshiprequest',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_to_mentee_set', to='mentorship_program_app.user'),
        ),
    ]
