# Generated by Django 5.0.1 on 2024-02-23 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship_program_app', '0013_remove_mentorshiprequest_mentee_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MentorshipRequest',
        ),
    ]
