# Generated by Django 5.0.1 on 2024-03-15 00:50

import django.db.models.deletion
import mentorship_program_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship_program_app', '0013_alter_mentorshiprequest_requester'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentor',
            old_name='organization',
            new_name='organizations',
        ),
        migrations.RemoveField(
            model_name='mentorshiprequest',
            name='requester',
        ),
        migrations.AlterField(
            model_name='profileimg',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile_img_query', serialize=False, to='mentorship_program_app.user'),
        ),
        migrations.AlterField(
            model_name='systemlogs',
            name='str_event',
            field=models.CharField(choices=[('User logged on', 'Logon Event'), ('Create mentorship', 'Approve Mentorship Event'), ('Request mentorship', 'Request Mentorship Event'), ('Mentorship terminated', 'Mentorship Terminated Event'), ('Mentee signed up', 'Mentee Register Event'), ('Mentor applied', 'Mentor Register Event'), ('Mentee deactivated', 'Mentee Deactivated Event'), ('Mentor deactivated', 'Mentor Deactivated Event')], default='', max_length=500),
        ),
        migrations.CreateModel(
            name='SuperAdminEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bool_enabled', models.BooleanField(default=True)),
                ('user_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_entry', to='mentorship_program_app.user')),
            ],
            bases=(mentorship_program_app.models.SVSUModelData, models.Model),
        ),
    ]
