# Generated by Django 5.0.1 on 2024-03-15 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship_program_app', '0014_rename_organization_mentor_organizations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorshiprequest',
            name='request',
            field=models.IntegerField(null=True),
        ),
    ]
