# Generated by Django 5.0.1 on 2024-03-15 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship_program_app', '0015_mentorshiprequest_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentorshiprequest',
            old_name='request',
            new_name='requester',
        ),
    ]
