# Generated by Django 5.0.1 on 2024-02-23 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship_program_app', '0015_mentorshiprequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MentorshipRequest',
        ),
    ]
