# Generated by Django 5.0.1 on 2024-02-23 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship_program_app', '0017_mentorshiprequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biographies',
            name='user',
        ),
        migrations.RemoveField(
            model_name='mentee',
            name='account',
        ),
        migrations.RemoveField(
            model_name='mentorshipreferral',
            name='mentee',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='account',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='orginization',
        ),
        migrations.RemoveField(
            model_name='mentorreports',
            name='mentor',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='admins',
        ),
        migrations.RemoveField(
            model_name='mentorshipreferral',
            name='mentor_to',
        ),
        migrations.RemoveField(
            model_name='mentorshipreferral',
            name='mentor_from',
        ),
        migrations.RemoveField(
            model_name='mentorshiprequest',
            name='mentee',
        ),
        migrations.RemoveField(
            model_name='mentorshiprequest',
            name='mentor',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='user',
        ),
        migrations.DeleteModel(
            name='SystemLogs',
        ),
        migrations.DeleteModel(
            name='Biographies',
        ),
        migrations.DeleteModel(
            name='Mentee',
        ),
        migrations.DeleteModel(
            name='MentorReports',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
        migrations.DeleteModel(
            name='Mentor',
        ),
        migrations.DeleteModel(
            name='MentorshipReferral',
        ),
        migrations.DeleteModel(
            name='MentorshipRequest',
        ),
        migrations.DeleteModel(
            name='Notes',
        ),
    ]
