# Generated by Django 5.0.1 on 2024-03-17 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship_program_app', '0010_alter_systemlogs_str_event'),
        ('mentorship_program_app', '0017_rename_organizations_mentor_organization'),
    ]

    operations = [
    ]
