# Generated by Django 5.0.1 on 2024-02-23 00:32

import datetime
import django.db.models.deletion
import mentorship_program_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship_program_app', '0018_remove_biographies_user_remove_mentee_account_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biographies',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mentorship_program_app.user')),
                ('str_bio', models.CharField(max_length=5000, null=True)),
            ],
            bases=(mentorship_program_app.models.SVSUModelData, models.Model),
        ),
        migrations.CreateModel(
            name='SystemLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str_event', models.CharField(max_length=500)),
                ('cls_log_created_on', models.DateField(default=datetime.date.today)),
            ],
            bases=(mentorship_program_app.models.SVSUModelData, models.Model),
        ),
        migrations.CreateModel(
            name='Mentee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mentorship_program_app.user')),
            ],
            bases=(mentorship_program_app.models.SVSUModelData, models.Model),
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_max_mentees', models.IntegerField(default=4)),
                ('int_recommendations', models.IntegerField(default=0)),
                ('str_job_title', models.CharField(max_length=100)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mentorship_program_app.user')),
            ],
            bases=(mentorship_program_app.models.SVSUModelData, models.Model),
        ),
        migrations.CreateModel(
            name='MentorReports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str_report_type', models.CharField(choices=[], default='', max_length=10)),
                ('str_report_body', models.CharField(max_length=3500)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentorship_program_app.mentor')),
            ],
            bases=(mentorship_program_app.models.SVSUModelData, models.Model),
        ),
        migrations.CreateModel(
            name='MentorshipReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentorship_program_app.mentee')),
                ('mentor_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_referrals_set', to='mentorship_program_app.mentor')),
                ('mentor_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_set', to='mentorship_program_app.mentor')),
            ],
            bases=(mentorship_program_app.models.SVSUModelData, models.Model),
        ),
        migrations.CreateModel(
            name='MentorshipRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentee_to_mentor_set', to='mentorship_program_app.user')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_to_mentee_set', to='mentorship_program_app.user')),
            ],
            bases=(mentorship_program_app.models.SVSUModelData, models.Model),
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str_note_title', models.CharField(max_length=100)),
                ('str_note_body', models.CharField(max_length=7000)),
                ('cls_note_created_on', models.DateField(default=datetime.date.today)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentorship_program_app.user')),
            ],
            bases=(mentorship_program_app.models.SVSUModelData, models.Model),
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str_org_name', models.CharField(max_length=100)),
                ('str_industry_type', models.CharField(max_length=100)),
                ('admins', models.ManyToManyField(to='mentorship_program_app.mentor')),
            ],
            bases=(mentorship_program_app.models.SVSUModelData, models.Model),
        ),
        migrations.AddField(
            model_name='mentor',
            name='orginization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentorship_program_app.organization'),
        ),
    ]
