# Generated by Django 5.0.1 on 2024-03-17 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship_program_app', '0018_merge_20240316_2003'),
        ('mentorship_program_app', '0019_remove_notes_str_body_notes_str_private_body_and_more'),
    ]

    operations = [
    ]
