# Generated by Django 5.0.1 on 2024-02-27 23:19

import django.db.models.deletion
import mentorship_program_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship_program_app', '0019_biographies_systemlogs_mentee_mentor_mentorreports_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intesest_set', to='mentorship_program_app.interest')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_set', to='mentorship_program_app.user')),
            ],
            bases=(mentorship_program_app.models.SVSUModelData, models.Model),
        ),
    ]
