# Generated by Django 5.0.1 on 2024-02-27 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship_program_app', '0020_user_interest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Interest',
        ),
    ]
