# Generated by Django 5.0.1 on 2024-03-18 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship_program_app', '0021_passwordresettoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='FastUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mentorship_program_app.user')),
                ('int_max_mentees', models.IntegerField(default=4)),
            ],
            options={
                'db_table': 'view_speed_test',
                'managed': False,
            },
            bases=('mentorship_program_app.user',),
        ),
    ]
