# Generated by Django 5.0.1 on 2024-03-18 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship_program_app', '0023_delete_fastuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='FastUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_max_mentees', models.IntegerField(default=4)),
            ],
            options={
                'db_table': 'view_speed_test',
                'managed': False,
            },
        ),
    ]
