# Generated by Django 5.0.1 on 2024-03-19 00:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mentorship_program_app", "0024_fastuser"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FastUser",
        ),
        migrations.AddField(
            model_name="mentorreports",
            name="bln_resolved",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="mentorreports",
            name="str_report_type",
            field=models.CharField(
                choices=[("Behavior", "Behavior")], default="", max_length=10
            ),
        ),
    ]
