# Generated by Django 5.0.1 on 2024-03-21 21:35

import django.db.models.deletion
import mentorship_program_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship_program_app', '0024_fastuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str_report_type', models.CharField(choices=[('Behavior', 'Behavior')], default='', max_length=10)),
                ('str_report_body', models.CharField(max_length=3500)),
                ('bln_resolved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentorship_program_app.user')),
            ],
            bases=(mentorship_program_app.models.SVSUModelData, models.Model),
        ),
        migrations.RemoveField(
            model_name='mentorreports',
            name='mentor',
        ),
        migrations.DeleteModel(
            name='FastUser',
        ),
        migrations.DeleteModel(
            name='MentorReports',
        ),
    ]
