# Generated by Django 5.0.1 on 2024-03-20 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship_program_app', '0025_delete_fastuser_alter_passwordresettoken_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorreports',
            name='mentee',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mentorship_program_app.mentee'),
        ),
    ]
