# Generated by Django 5.0.1 on 2024-03-26 18:53

import mentorship_program_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship_program_app', '0027_userreport_delete_mentorreports'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhitelistedEmails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str_report_body', models.CharField(max_length=320)),
            ],
            bases=(mentorship_program_app.models.SVSUModelData, models.Model),
        ),
    ]
