# Generated by Django 5.0.1 on 2024-03-27 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship_program_app', '0028_whitelistedemails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whitelistedemails',
            old_name='str_report_body',
            new_name='str_email',
        ),
    ]
