# Generated by Django 5.0.1 on 2024-03-30 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship_program_app', '0029_rename_str_report_body_whitelistedemails_str_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='admins',
        ),
        migrations.AddField(
            model_name='organization',
            name='admin',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='administered_organizations', to='mentorship_program_app.mentor'),
        ),
    ]
