# Generated by Django 5.0.1 on 2024-03-30 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship_program_app', '0030_remove_organization_admins_organization_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='admin',
            new_name='admin_mentor',
        ),
    ]
