# Generated by Django 5.0.1 on 2024-04-09 17:18

import datetime
import mentorship_program_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship_program_app', '0031_rename_admin_organization_admin_mentor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strCompany', models.CharField(max_length=100, unique=True)),
            ],
            bases=(mentorship_program_app.models.SVSUModelData, models.Model),
        ),
        migrations.AlterField(
            model_name='notes',
            name='cls_created_on',
            field=models.DateField(default=datetime.date(2024, 4, 9)),
        ),
        migrations.AlterField(
            model_name='systemlogs',
            name='cls_log_created_on',
            field=models.DateField(default=datetime.date(2024, 4, 9)),
        ),
        migrations.AlterField(
            model_name='user',
            name='cls_active_changed_date',
            field=models.DateField(default=datetime.date(2024, 4, 9)),
        ),
        migrations.AlterField(
            model_name='user',
            name='cls_date_joined',
            field=models.DateField(default=datetime.date(2024, 4, 9)),
        ),
        migrations.AlterField(
            model_name='user',
            name='str_last_login_date',
            field=models.DateField(default=datetime.date(2024, 4, 9)),
        ),
    ]
