# Generated by Django 5.0.1 on 2024-04-09 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship_program_app', '0035_systemlogs_str_details_alter_systemlogs_str_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemlogs',
            name='str_event',
            field=models.CharField(choices=[('User logged on', 'Logon Event'), ('Create mentorship', 'Approve Mentorship Event'), ('Request mentorship', 'Request Mentorship Event'), ('Mentorship terminated', 'Mentorship Terminated Event'), ('Mentee signed up', 'Mentee Register Event'), ('Mentor applied', 'Mentor Register Event'), ('Mentee deactivated', 'Mentee Deactivated Event'), ('Mentor deactivated', 'Mentor Deactivated Event'), ('Interest created', 'Interests Created Event'), ('Interest updated', 'Interests Updated Event'), ('Interest deleted', 'Interests Deleted Event'), ('Mentor approved', 'Mentor Approved Event'), ('Mentor denied', 'Mentor Denied Event')], default='', max_length=500),
        ),
    ]
