# Generated by Django 5.0.1 on 2024-04-09 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship_program_app', '0036_alter_systemlogs_str_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemlogs',
            name='cls_log_created_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
