# Generated by Django 5.0.1 on 2024-04-09 06:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship_program_app', '0039_alter_systemlogs_cls_log_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemlogs',
            name='cls_log_created_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
