# Generated by Django 5.0.1 on 2024-04-09 06:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship_program_app', '0040_alter_systemlogs_cls_log_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemlogs',
            name='cls_log_created_on_full',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
