# Generated by Django 5.0.1 on 2024-04-09 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship_program_app', '0041_systemlogs_cls_log_created_on_full'),
    ]

    operations = [
        migrations.RenameField(
            model_name='systemlogs',
            old_name='cls_log_created_on_full',
            new_name='cls_log_created_on_sortable',
        ),
    ]
