# Generated by Django 5.0.1 on 2024-04-09 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship_program_app', '0032_company_alter_notes_cls_created_on_and_more'),
        ('mentorship_program_app', '0043_alter_systemlogs_str_event'),
    ]

    operations = [
    ]
