# Generated by Django 5.0.1 on 2024-04-09 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship_program_app', '0043_alter_systemlogs_str_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='str_phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
