# Generated by Django 5.0.1 on 2024-04-10 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship_program_app', '0046_company_strtype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
    ]
