# Generated by Django 5.0.1 on 2024-04-10 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship_program_app', '0046_userreport_resolved_comment_and_more'),
        ('mentorship_program_app', '0047_delete_company'),
    ]

    operations = [
    ]
