# Generated by Django 5.0.1 on 2024-04-10 20:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship_program_app', '0048_merge_20240410_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreport',
            name='date_reported',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userreport',
            name='date_resolved',
            field=models.DateField(null=True),
        ),
    ]
