# Generated by Django 5.0.1 on 2024-04-15 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship_program_app', '0049_userreport_date_reported_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemlogs',
            name='str_event',
            field=models.CharField(choices=[('User logged on', 'Logon Event'), ('Create mentorship', 'Approve Mentorship Event'), ('Request mentorship', 'Request Mentorship Event'), ('Mentorship terminated', 'Mentorship Terminated Event'), ('Mentee signed up', 'Mentee Register Event'), ('Mentor applied', 'Mentor Register Event'), ('Mentee deactivated', 'Mentee Deactivated Event'), ('Mentor deactivated', 'Mentor Deactivated Event'), ('Interest created', 'Interests Created Event'), ('Interest updated', 'Interests Updated Event'), ('Interest deleted', 'Interests Deleted Event'), ('Mentor approved', 'Mentor Approved Event'), ('Mentor denied', 'Mentor Denied Event'), ('Report resolved', 'Report Resolved Event'), ('Report created', 'Report Created Event'), ('Mentee inactivated', 'Mentee Inactivated Event'), ('Mentor inactivated', 'Mentor Inactivated Event'), ('Organization deleted', 'Organization Deleted Event'), ('Organization added', 'Organization Created Event'), ("Mentor's organization changed", 'Mentor Organization Changed Event'), ("User's reports were resolved automatically", 'Auto Resolve Event')], default='', max_length=500),
        ),
        migrations.DeleteModel(
            name='MentorshipReferral',
        ),
    ]
