- name: Create kubernetes secrets file
  template:
    src: ./ansible/roles/secrets/tasks/templates/mentor-secret.yaml
    dest: ./kubernetes/mentor-secret.yaml

- name: Create kubernetes configmap file
  template:
    src: ./ansible/roles/secrets/tasks/templates/mentor-configmap.yaml
    dest: ./kubernetes/mentor-configmap.yaml
