apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup
spec:
  schedule: "{{ backup_cron_string }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: web
            image: localhost:5000/project-kubernetes
            envFrom:
            - secretRef:
                name: mentor-secret
            - configMapRef:
                name: mentor-config
            volumeMounts:
            - mountPath: "{{ media_root }}"
              name: media-volume
            - mountPath: "{{ backup_root }}"
              name: backup-volume
            command:
            - /bin/sh
            - -c
            - python /mentorship_program/mentorship_program_project/manage.py runscript create_database_backup
          restartPolicy: OnFailure
          volumes:
            - name: media-volume
              persistentVolumeClaim:
                claimName: media-pvc
            - name: backup-volume
              persistentVolumeClaim:
                claimName: backup-pvc
