all:
  children:
    staging:
      hosts:
        staging01:
          ansible_host: 127.0.0.1
          ansible_user: user
      vars:
        
        database_server:
          - staging01
        nfs_server:
          - staging01
        k3s_server:
          - staging01
        docker_repo_server:
          - staging01

    production:
      hosts:
        prod01: 
          ansible_host: 127.0.0.1
          ansible_user: user
      vars:
        database_server:
          - prod01
        nfs_server:
          - prod01
        k3s_server:
          - prod01
        docker_repo_server:
          - prod01