- name: Master playbook
  hosts: localhost
  gather_facts: false
  become: true
  

  #TODO: switch to using ansible vault
#- import_playbook: ./env-setup.yaml
- import_playbook: ./postgres-setup.yaml
- import_playbook: ./nfs-setup.yaml
- import_playbook: ./docker-repo-setup.yaml
- import_playbook: ./docker-build.yaml
- import_playbook: ./k3s-secret.yaml
- import_playbook: ./k3s-setup.yaml
