- name: Clone / pull git repo
  ansible.builtin.git:
    repo: 'https://github.com/adamuremek/mentorship-program.git'
    dest: "{{ absolute_project_path }}/repo"
    update: yes
    version: "{{ git_branch }}"

- name: Create saml directory
  file:
    path: "{{ absolute_project_path }}/mentorship_program_project/saml"
    state: directory

- name: Check for saml private key
  stat:
    path: "{{ absolute_project_path }}/mentorship_program_project/saml/private.key"
  register: saml_private_key

- name: Check for saml public key
  stat:
    path: "{{ absolute_project_path }}/mentorship_program_project/saml/public.pem"
  register: saml_public_key

- name: Generate saml private key
  community.crypto.openssl_privatekey:
    path: "{{ absolute_project_path }}/mentorship_program_project/saml/private.key"
    type: RSA
    size: 2048
  when: not saml_private_key.stat.exists    

- name: Generate saml public key
  community.crypto.openssl_publickey:
    path: "{{ absolute_project_path }}/mentorship_program_project/saml/public.pem"
    privatekey_path: "{{ absolute_project_path }}/mentorship_program_project/saml/private.key"
  when: not saml_public_key.stat.exists
  
- name: Check for remote_metadata.xml
  stat:
    path: "{{ absolute_project_path }}/mentorship_program_project/saml/remote_metadata.xml"
  register: remote_metadata

- name: Download remote_metadata.xml
  get_url:
    url: "{{ saml_idp_metadata_url }}"
    dest: "{{ absolute_project_path }}/mentorship_program_project/saml/remote_metadata.xml"
  when: not remote_metadata.stat.exists

- name: make directory for saml files
  file:
    path: "/{{ absolute_project_path }}/repo/mentorship_program_project/saml"
    state: directory

- name: Copy saml files into project directory
  copy:
    src: "{{ item }}"
    dest: "/{{ absolute_project_path }}/repo/mentorship_program_project/saml/{{ item | basename }}"
    remote_src: true
  with_items:
    - "{{ absolute_project_path }}/mentorship_program_project/saml/private.key"
    - "{{ absolute_project_path }}/mentorship_program_project/saml/public.pem"
    - "{{ absolute_project_path }}/mentorship_program_project/saml/remote_metadata.xml"
  become: true
