- name: Check if env.yaml is exists
  stat:
    path: "{{ local_env_file_path }}"
  register: env_file_stat 

- name: Fail if env.yaml is missing
  fail:
    msg: "The {{ local_env_file_path }} file is missing. Create it using env-template.yaml"
  when: not env_file_stat.stat.exists

- name: Make sure remote env exists
  file:
    path: "{{ remote_env_file_path }}"
    state: touch
    mode: '0600'

- name: Set environment variables from .env file
  lineinfile:
    dest: "{{ remote_env_file_path }}"
    line: "export {{ item }}"
    regexp: "^{{ item.split(':')[0] }}="
  with_items: "{{ lookup('file', '{{ local_env_file_path }}').splitlines() }}"
