name: Deploy
on:
  push:
    branches: [dev-main]
jobs:
  deploy:
    if: github.repository == 'adamuremek/mentorship-program'
    runs-on: self-hosted
    steps:
      - name: Run update script
        run: /home/k3suser/mentorship-program/ansible/update.sh
        
